import type { HumanControlInventory } from "@codesign-commerce/core";

export const toteHumanControlInventory: HumanControlInventory = {
  schemaVersion: "1.0",
  integrationId: "codesign.studio-tote-reference.web",
  manifestId: "codesign.studio-tote-reference",
  inventoryVersion: "2026-08-27.1",
  auditedAt: "2026-08-27",
  controls: [
    {
      id: "product.change",
      label: "Change product",
      selector: ".product-card button",
      kind: "button",
      mapping: { kind: "excluded", category: "non-configurational", reason: "Product discovery sits outside the open tote configurator fixture." },
    },
    {
      id: "variant.tabs",
      label: "Choose tote variant",
      selector: "[data-variant-tabs] [role='tab']",
      kind: "tablist",
      mapping: { kind: "variant-operation", operation: "set-active" },
    },
    {
      id: "variant.add",
      label: "Add tote variant",
      selector: "[data-variant-tabs] .add-variant",
      kind: "button",
      mapping: { kind: "variant-operation", operation: "duplicate" },
    },
    {
      id: "variant.name",
      label: "Variant name",
      selector: "[data-variant-name]",
      kind: "input",
      mapping: { kind: "control", controlId: "design.name" },
    },
    {
      id: "step.navigation",
      label: "Configurator step navigation",
      selector: "[data-step-target]",
      kind: "button",
      mapping: { kind: "excluded", category: "navigation", reason: "Step buttons only scroll the existing page and do not change product state." },
    },
    {
      id: "canvas.weight",
      label: "Canvas weight",
      selector: "[data-choice-group='canvas.weight']",
      kind: "button",
      mapping: { kind: "control", controlId: "canvas.weight" },
    },
    {
      id: "bag.color",
      label: "Body colour",
      selector: "[data-choice-group='bag.color']",
      kind: "button",
      mapping: { kind: "control", controlId: "bag.color" },
    },
    {
      id: "handles.length",
      label: "Handle length",
      selector: "[data-choice-group='handles.length']",
      kind: "button",
      mapping: { kind: "control", controlId: "handles.length" },
    },
    {
      id: "construction.reinforced",
      label: "Reinforced construction",
      selector: "input[data-option='construction.reinforced']",
      kind: "checkbox",
      mapping: { kind: "control", controlId: "construction.reinforced" },
    },
    {
      id: "print.position",
      label: "Print placement",
      selector: "select[data-option='print.position']",
      kind: "select",
      mapping: { kind: "control", controlId: "print.position" },
    },
    {
      id: "print.method",
      label: "Print method",
      selector: "select[data-option='print.method']",
      kind: "select",
      mapping: { kind: "control", controlId: "print.method" },
    },
    {
      id: "design.quantity",
      label: "Variant quantity",
      selector: "input[data-option='design.quantity']",
      kind: "input",
      mapping: { kind: "control", controlId: "design.quantity" },
    },
    {
      id: "proposal.keep",
      label: "Keep agent proposal",
      selector: "[data-codesign-review] button.primary",
      kind: "button",
      mapping: { kind: "excluded", category: "human-confirmation", reason: "Keep is deliberately reserved for a person and is never an agent-writable control." },
    },
    {
      id: "proposal.revert",
      label: "Revert agent proposal",
      selector: "[data-codesign-review] button.secondary",
      kind: "button",
      mapping: { kind: "excluded", category: "human-confirmation", reason: "Revert is deliberately reserved for a person and is never an agent-writable control." },
    },
    {
      id: "native.asset.file",
      label: "Native asset proof file chooser",
      selector: "[data-native-asset-file]",
      kind: "file-input",
      mapping: { kind: "excluded", category: "development-only", reason: "This chooser appears only in the local native WebMCP evidence route; agents use the bounded asset slot." },
    },
    {
      id: "native.proof.run",
      label: "Run native WebMCP proof",
      selector: "[data-native-webmcp-run]",
      kind: "button",
      mapping: { kind: "excluded", category: "development-only", reason: "This diagnostic action appears only when a local evidence query flag is enabled." },
    },
  ],
};
