import type { HumanControlInventory } from "@codesign-webmcp/core";

export const toteHumanControlInventory: HumanControlInventory = {
  schemaVersion: "1.0",
  integrationId: "codesign.studio-tote-reference.web",
  manifestId: "codesign.studio-tote-reference",
  inventoryVersion: "2026-08-27.2",
  auditedAt: "2026-08-27",
  controls: [
    {
      id: "fixture.reset",
      label: "Reset public fixture",
      selector: "button[data-reset-design]",
      kind: "button",
      mapping: { kind: "excluded", category: "non-configurational", reason: "Reset clears only the fictional local reference fixture and is not product configuration." },
    },
    {
      id: "variant.tabs",
      label: "Choose tote variant",
      selector: "[data-variant-tabs] [role='tab']",
      kind: "tablist",
      mapping: { kind: "variant-operation", operation: "set-active" },
    },
    {
      id: "variant.add",
      label: "Add tote variant",
      selector: "[data-variant-tabs] .add-variant",
      kind: "button",
      mapping: { kind: "variant-operation", operation: "duplicate" },
    },
    {
      id: "variant.preview",
      label: "Choose tote variant from preview rail",
      selector: "[data-variant-previews] .preview-card",
      kind: "tablist",
      mapping: { kind: "variant-operation", operation: "set-active" },
    },
    {
      id: "variant.mobile-tabs",
      label: "Choose tote variant above the mobile canvas",
      selector: "[data-mobile-variant-tabs]",
      kind: "tablist",
      mapping: { kind: "variant-operation", operation: "set-active" },
    },
    {
      id: "variant.name",
      label: "Variant name",
      selector: "[data-variant-name]",
      kind: "input",
      mapping: { kind: "control", controlId: "design.name" },
    },
    {
      id: "step.navigation",
      label: "Configurator step navigation",
      selector: "[data-step-target]",
      kind: "button",
      mapping: { kind: "excluded", category: "navigation", reason: "Step buttons only scroll the existing page and do not change product state." },
    },
    {
      id: "canvas.weight",
      label: "Canvas weight",
      selector: "[data-choice-group='canvas.weight']",
      kind: "button",
      mapping: { kind: "control", controlId: "canvas.weight" },
    },
    {
      id: "bag.color",
      label: "Body colour",
      selector: "[data-choice-group='bag.color']",
      kind: "button",
      mapping: { kind: "control", controlId: "bag.color" },
    },
    {
      id: "handles.length",
      label: "Handle length",
      selector: "[data-choice-group='handles.length']",
      kind: "button",
      mapping: { kind: "control", controlId: "handles.length" },
    },
    {
      id: "construction.reinforced",
      label: "Reinforced construction",
      selector: "input[data-option='construction.reinforced']",
      kind: "checkbox",
      mapping: { kind: "control", controlId: "construction.reinforced" },
    },
    {
      id: "print.position",
      label: "Print placement",
      selector: "select[data-option='print.position']",
      kind: "select",
      mapping: { kind: "control", controlId: "print.position" },
    },
    {
      id: "print.method",
      label: "Print method",
      selector: "select[data-option='print.method']",
      kind: "select",
      mapping: { kind: "control", controlId: "print.method" },
    },
    {
      id: "branding.text",
      label: "Studio name text",
      selector: "input[data-option='branding.text']",
      kind: "input",
      mapping: { kind: "control", controlId: "branding.text" },
    },
    {
      id: "branding.typeface",
      label: "Studio-name typography",
      selector: "select[data-option='branding.typeface']",
      kind: "select",
      mapping: { kind: "control", controlId: "branding.typeface" },
    },
    {
      id: "branding.ink-color",
      label: "Branding ink colour",
      selector: "[data-choice-group='branding.ink_color']",
      kind: "button",
      mapping: { kind: "control", controlId: "branding.ink_color" },
    },
    {
      id: "branding.scale",
      label: "Artwork scale",
      selector: "input[data-option='branding.scale']",
      kind: "input",
      mapping: { kind: "control", controlId: "branding.scale" },
    },
    {
      id: "branding.rotation",
      label: "Artwork rotation",
      selector: "input[data-option='branding.rotation']",
      kind: "input",
      mapping: { kind: "control", controlId: "branding.rotation" },
    },
    {
      id: "branding.artwork-file",
      label: "Supplied artwork file",
      selector: "input[data-artwork-file]",
      kind: "file-input",
      mapping: { kind: "asset-slot", slotId: "print-artwork" },
    },
    {
      id: "branding.artwork-remove",
      label: "Remove supplied artwork",
      selector: "button[data-artwork-remove]",
      kind: "button",
      mapping: { kind: "control", controlId: "branding.artwork_ref" },
    },
    {
      id: "design.quantity",
      label: "Variant quantity",
      selector: "input[data-option='design.quantity']",
      kind: "input",
      mapping: { kind: "control", controlId: "design.quantity" },
    },
    {
      id: "proposal.keep",
      label: "Keep agent proposal",
      selector: "[data-codesign-review] button.primary",
      kind: "button",
      mapping: { kind: "excluded", category: "human-confirmation", reason: "Keep is deliberately reserved for a person and is never an agent-writable control." },
    },
    {
      id: "proposal.revert",
      label: "Revert agent proposal",
      selector: "[data-codesign-review] button.secondary",
      kind: "button",
      mapping: { kind: "excluded", category: "human-confirmation", reason: "Revert is deliberately reserved for a person and is never an agent-writable control." },
    },
    {
      id: "native.asset.file",
      label: "Native asset proof file chooser",
      selector: "[data-native-asset-file]",
      kind: "file-input",
      mapping: { kind: "excluded", category: "development-only", reason: "This chooser appears only in the local native WebMCP evidence route; agents use the bounded asset slot." },
    },
    {
      id: "native.proof.run",
      label: "Run native WebMCP proof",
      selector: "[data-native-webmcp-run]",
      kind: "button",
      mapping: { kind: "excluded", category: "development-only", reason: "This diagnostic action appears only when a local evidence query flag is enabled." },
    },
  ],
};
