import type { ConfigurationState, ConfiguratorManifest } from "../src/index.js";

export const testManifest: ConfiguratorManifest = {
  schemaVersion: "2.0",
  id: "codesign.test-configurator",
  version: "1.0.0",
  displayName: "Test configurator",
  productType: "test-product",
  controls: [
    {
      id: "body.color",
      label: "Body colour",
      agentDescription: "Choose the main body colour.",
      scope: "variant",
      kind: "enum",
      agentWritable: true,
      requirement: "configuration",
      values: [
        { id: "cream", label: "Cream" },
        { id: "navy", label: "Navy" },
        { id: "rose", label: "Dusty rose" },
      ],
    },
    {
      id: "accent.color",
      label: "Accent colour",
      agentDescription: "Choose the accent colour.",
      scope: "variant",
      kind: "enum",
      agentWritable: true,
      requirement: "configuration",
      values: [
        { id: "navy", label: "Navy" },
        { id: "berry", label: "Berry" },
        { id: "cream", label: "Cream" },
      ],
    },
    {
      id: "design.name",
      label: "Design name",
      agentDescription: "Set a public name for one design or colourway.",
      scope: "variant",
      kind: "text",
      role: "variant-name",
      agentWritable: true,
      requirement: "configuration",
      maximumLength: 60,
    },
    {
      id: "design.quantity",
      label: "Design quantity",
      agentDescription: "Set the pair quantity for one design.",
      scope: "variant",
      kind: "integer",
      role: "variant-quantity",
      agentWritable: true,
      requirement: "configuration",
      minimum: 20,
      maximum: 10000,
    },
    {
      id: "order.total_quantity",
      label: "Order quantity",
      agentDescription: "Set the total quantity across all designs.",
      scope: "workspace",
      kind: "integer",
      role: "workspace-total",
      agentWritable: true,
      requirement: "configuration",
      minimum: 20,
      maximum: 10000,
    },
    {
      id: "branding.artwork_status",
      label: "Artwork status",
      agentDescription: "Read whether final artwork is ready.",
      scope: "variant",
      kind: "enum",
      agentWritable: false,
      requirement: "production-readiness",
      values: [
        { id: "missing", label: "Missing" },
        { id: "placeholder", label: "Placeholder" },
        { id: "ready", label: "Ready" },
      ],
    },
  ],
  assetSlots: [],
  variantPolicy: {
    minimumVariants: 1,
    maximumVariants: 4,
    operations: ["duplicate", "set-active"],
  },
  previewSurfaces: [{
    id: "product-preview",
    label: "Product preview",
    scope: "variant",
    mediaTypes: ["image/webp"],
    maximumBytes: 1_500_000,
  }],
  dependencyDescriptions: [],
  approval: {
    mode: "explicit-human",
    persistencePath: "page-keep-controller",
  },
};

export const testState: ConfigurationState = {
  configuratorId: testManifest.id,
  manifestVersion: testManifest.version,
  revision: "revision-1",
  activeDesignId: "design-1",
  order: { totalQuantity: 60 },
  designs: [
    {
      id: "design-1",
      name: "Design 1",
      quantity: 60,
      selections: {
        "body.color": "cream",
        "accent.color": "navy",
      },
      assets: [{ slot: "logo", status: "missing", agentWritable: false }],
    },
  ],
};
